#!/usr/bin/env python3
"""
KPI Report Generator
Generates a performance report for Dhamma Channel
"""

import sys
import os
import argparse
from pathlib import Path
from datetime import datetime

# Add src to python path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from agents.analytics_agent import AnalyticsAgent, AnalyticsInput
from agents.analytics_agent.adapter import YouTubeAnalyticsAdapter
from agents.analytics_agent.mock import MockYouTubeAnalyticsAdapter
from automation_core.config import config

def generate_html_report(output_data, output_file: Path):
    """Generate HTML Report"""
    
    html = f"""
    <!DOCTYPE html>
    <html lang="th">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Dhamma Channel KPI Report</title>
        <style>
            body {{ font-family: 'Sarabun', sans-serif; margin: 0; padding: 20px; background: #f5f5f5; }}
            .container {{ max-width: 1000px; margin: 0 auto; background: white; padding: 40px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }}
            h1 {{ color: #4a5568; border-bottom: 2px solid #e2e8f0; padding-bottom: 15px; }}
            h2 {{ color: #2d3748; margin-top: 30px; }}
            .stats-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin: 30px 0; }}
            .stat-card {{ background: #ebf8ff; padding: 20px; border-radius: 8px; text-align: center; }}
            .stat-value {{ font-size: 2.5em; font-weight: bold; color: #3182ce; }}
            .stat-label {{ color: #718096; font-size: 0.9em; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
            th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #e2e8f0; }}
            th {{ background-color: #f7fafc; color: #4a5568; }}
            .video-rank {{ font-weight: bold; color: #718096; }}
            .metric-good {{ color: #38a169; }}
            .date-range {{ background: #edf2f7; padding: 10px 20px; border-radius: 20px; display: inline-block; font-size: 0.9em; color: #4a5568; }}
        </style>
        <link href="https://fonts.googleapis.com/css2?family=Sarabun:wght@400;500;700&display=swap" rel="stylesheet">
    </head>
    <body>
        <div class="container">
            <h1>📊 Dhamma Channel Performance Report</h1>
            <div class="date-range">📅 Period: {output_data.start_date} to {output_data.end_date}</div>
            
            <div class="stats-grid">
                <div class="stat-card">
                    <div class="stat-value">{output_data.total_views:,}</div>
                    <div class="stat-label">Total Views</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">{output_data.total_watch_time_minutes:,}</div>
                    <div class="stat-label">Watch Time (Mins)</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">+{output_data.total_subscribers_gained:,}</div>
                    <div class="stat-label">New Subscribers</div>
                </div>
            </div>

            <h2>🏆 Top Performing Videos</h2>
            <table>
                <thead>
                    <tr>
                        <th width="50">#</th>
                        <th>Video Title</th>
                        <th width="100">Views</th>
                        <th width="100">Likes</th>
                        <th width="100">Comments</th>
                    </tr>
                </thead>
                <tbody>
    """
    
    for i, video in enumerate(output_data.top_videos, 1):
        html += f"""
                    <tr>
                        <td class="video-rank">{i}</td>
                        <td>{video.title} <br><span style="font-size:0.8em; color:#a0aec0;">ID: {video.video_id}</span></td>
                        <td class="metric-good">{video.views:,}</td>
                        <td>{video.likes:,}</td>
                        <td>{video.comments:,}</td>
                    </tr>
        """
        
    html += """
                </tbody>
            </table>
            
            <div style="margin-top: 40px; text-align: center; color: #a0aec0; font-size: 0.8em;">
                Generated by AnalyticsAgent v1.0 • Dhamma Channel Automation
            </div>
        </div>
    </body>
    </html>
    """
    
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(html)
    
    print(f"✅ Report generated: {output_file}")


def main():
    parser = argparse.ArgumentParser(description="Generate KPI Report")
    parser.add_argument("--days", default="30d", help="Date range (7d, 30d, 90d)")
    parser.add_argument("--out", default="reports/kpi_report.html", help="Output file path")
    parser.add_argument("--dry-run", action="store_true", help="Use mock data without API calls")
    
    args = parser.parse_args()
    
    print(f"🚀 Starting KPI Report Generator ({args.days})")
    
    if args.dry_run:
        print("🔧 Mode: DRY RUN (Mock Data)")
        adapter = MockYouTubeAnalyticsAdapter()
    else:
        print("🔧 Mode: PRODUCTION (Real API)")
        # Load credentials setup
        creds_json = Path(os.getenv("GOOGLE_APPLICATION_CREDENTIALS", "client_secret.json")) # Default lookup
        token_pickle = Path("youtube_token.pickle")
        
        # Check if secrets exist (simple check, adapter does more)
        if not creds_json.exists() and not token_pickle.exists():
            print(f"❌ Credentials not found at {creds_json}")
            print("   Please enable YouTube Analytics API and download client_secret.json")
            return 1
            
        adapter = YouTubeAnalyticsAdapter(creds_json, token_pickle)
        
        try:
            adapter.authenticate()
        except Exception as e:
            print(f"❌ Authentication failed: {e}")
            return 1

    agent = AnalyticsAgent(adapter=adapter)
    
    try:
        input_data = AnalyticsInput(date_range=args.days)
        result = agent.run(input_data)
        
        # Generate HTML
        output_path = Path(args.out)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        generate_html_report(result, output_path)
        
    except Exception as e:
        print(f"❌ Error generating report: {e}")
        return 1
        
    return 0

if __name__ == "__main__":
    sys.exit(main())
